SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 1080

MENU_OPTIONS_WIDTH = 300
MENU_OPTIONS_HEIGHT = 300

GAME_OVER_TEXT_WIDTH = 100
GAME_OVER_TEXT_HEIGHT = 100

#Assets
IMG_WIDTH = 40
IMG_HEIGHT = 40
BRIDGE_WIDTH = 120
BRIDGE_HEIGHT = 30



#number of tiles in screen: horizontal and vertical
NUM_TILES_HORIZONTAL_SCR = SCREEN_WIDTH // IMG_WIDTH
NUM_TILES_VERTICAL_SCR = SCREEN_HEIGHT // IMG_HEIGHT

#level size
NUM_TILES_LVL_HORIZONTAL = 100
NUM_TILES_LVL_VERTICAL = 40
LVL_WIDTH = NUM_TILES_LVL_HORIZONTAL * IMG_WIDTH
LVL_HEIGHT = NUM_TILES_LVL_VERTICAL * IMG_HEIGHT

